title: <p align="center"> Piyush Kumar Agrawal </p>
logo: /assets/img/Piyush_Kumar_Agrawal.jpg
description: Fraud Detection is a machine Learning Project.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
